# This file contains configuration that users should not modify.
resources:
  SciGRID_gas: https://zenodo.org/records/4767098/files/IGGIELGN.zip
  spatial_units: https://www.dropbox.com/scl/fi/ijfihaqy5eki13nplvrn4/units-ehighways.geojson?rlkey=q0agmofhaklt1pytzef59o1xq&e=1&dl=0


resolution: e_highways
